language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo build --verbose --manifest-path lpc11uxx/Cargo.toml; fi
  - cargo build --verbose --manifest-path lpc82x/Cargo.toml
  - cargo build --verbose --manifest-path lpc845/Cargo.toml
  - cargo build --verbose --manifest-path lpc176x5x/Cargo.toml

