[package]
name    = "lpc82x-pac"
version = "0.8.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"

description   = "Low-level register mappings for the NXP LPC82x series of ARM Cortex-M0+ microcontrollers"
documentation = "https://docs.rs/lpc82x-pac"
repository    = "https://github.com/lpc-rs/lpc-pac"
license       = "0BSD"
readme        = "README.md"
categories    = ["embedded", "hardware-support", "no-std"]
keywords      = ["arm", "cortex-m", "nxp", "lpc", "svd2rust"]


[badges]
travis-ci   = { repository = "lpc-rs/lpc-pac" }


[dependencies]
cortex-m    = "0.7.2"
cortex-m-rt = { version = ">=0.6, <0.8", optional = true }
vcell       = "0.1.2"


[features]
rt = ["cortex-m-rt", "cortex-m-rt/device"]
