#!/usr/bin/env bash

cargo install --force --version 0.12.1 svd2rust &&
cargo install --force --version 0.6.1 rustfmt-nightly &&

wget \
	-O LPC82x.svd \
	http://ds.arm.com/media/resources/db/chip/nxp/lpc824m201jdh20/LPC82x.svd &&

for patch in patches/*
do
	patch \
		--silent \
		--force \
		--reject-file=- \
		LPC82x.svd $patch
done

mkdir -p src &&
svd2rust -i LPC82x.svd | rustfmt > src/lib.rs
