name: compare mmaps

env:
  SVDTOOLS_VERSION: 0.2.1

on:
  pull_request_target:

jobs:
  compare:
    name: Compare mmaps
    runs-on: ubuntu-18.04
    continue-on-error: true

    env:
      SVDTOOLS: svdtools

    steps:
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          path: master

      - name: Checkout pull request
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.number }}/head
          path: pr

      - name: Checkout mmaps
        uses: actions/checkout@v3
        with:
          repository: lpc-rs/lpc-pac-mmaps
          ssh-key: ${{ secrets.MMAPS_KEY }}
          path: mmaps

      - name: Add fictive crate
        run: |
          cargo init
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
        with:
          key: svdtools-${{ env.SVDTOOLS_VERSION }}

      - name: Install svdtools
        run: |
          cargo install svdtools --version $SVDTOOLS_VERSION
      - name: Build and publish
        run: |
          # Grab commit ID from checked out PR
          cd pr
          COMMIT=$(git rev-parse --short HEAD)
          BRANCH=pr-${{ github.event.number }}-$COMMIT
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          # Use the PR's YAML files to rebuild mmaps
          cd ../master
          rm -rf devices
          mv ../pr/devices .
          make -j2 mmaps
          # Use the new mmaps to make a commit in the mmaps repo
          mv mmaps/* ../mmaps/
          cd ../mmaps
          git checkout -b $BRANCH
          git add .
          git config user.name "lpc-pac builder"
          git config user.email "action@github.com"
          git commit --allow-empty -m "lpc-pac PR #${{ github.event.number }} $COMMIT"
          git push origin $BRANCH
      - name: Comment
        uses: mshick/add-pr-comment@v1
        with:
          message: |
            [Memory map comparison](https://github.com/lpc-rs/lpc-pac-mmaps/compare/${{ env.BRANCH }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'